;; (setq l '(azi e soare))
;; (remove 'soare l)
;; (delete 'soare l)
;; (setq *ll* '(a b c d))
;; (subst 'a 'b '(a b (b (d e f) b ) b))
;; (setq w '(1 + 1 + 1 = 3))
(defun egal (l1 l2)
    (cond (( and (null l1) (null l2)) t)
        ((and (atom l1) (atom l2)) (equal l1 l2))
        ((and (atom l1) (not (atom l2))) nil)
        ((and (not atom l1) (atom l2)) nil)
        ((egal (car l1) (car l2)) (egal (cdr l1) (cdr l2)))
        (t nil)
    )
)

